FROM python:3.9-slim-bullseye

ARG SALT_VERSION=3006

RUN apt-get update && \
    apt-get install --no-install-recommends -y openssh-client openssh-server gcc g++ autoconf make libffi-dev libssl-dev && \
    apt-get clean && \
    pip install --no-cache-dir pip setuptools wheel poetry --upgrade && \
	pip install --no-cache-dir salt-nornir[prodmaxminion] && \
	USE_STATIC_REQUIREMENTS=1 pip install --no-cache-dir salt==${SALT_VERSION}

ENTRYPOINT salt-proxy --proxyid=$PROXY_ID -l $LOG_LEVEL