FROM rockylinux:8.5

# install misc libs
RUN dnf install -y python3.9 nano tree
RUN python3 -m pip install pip setuptools wheel --upgrade

ARG SALT_VERSION=3004

# install SALT
RUN python3 -m pip install salt==${SALT_VERSION}

# do python libs installation
RUN python3 -m pip install salt-nornir[prodmin]

ENTRYPOINT salt-master -l $LOG_LEVEL