FROM rockylinux:8.5

# install misc libs
RUN dnf install -y python3.9 nano tree openssh-server openssh-clients
RUN python3 -m pip install pip setuptools wheel --upgrade

ARG SALT_VERSION=3004

# install SALT
RUN python3 -m pip install salt==${SALT_VERSION}

# do python libs installation
RUN python3 -m pip install salt-nornir[prodmax]

ENTRYPOINT salt-proxy --proxyid=$PROXY_ID -l $LOG_LEVEL